{
 "title": "C3P Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Pending and Total Finished in the week",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Count(i.inspection_id) AS total_pending\n  FROM c3p.inspection i\n  WHERE \n  (i.start_date < current_date - interval '7 days' and i.finish_date isnull) or i.start_date > current_date - interval '7 days';"
    },
    {
     "rawSql": "SELECT\n  Count(i.inspection_id) as total_finished_week\n  from c3p.inspection i\n  where i.start_date > current_date - interval '7 days' and i.finish_date is not null;"
    }
   ]
  },
  {
   "title": "Finished process time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(minutes) AS minimum, MAX(minutes) AS maximum, avg(minutes) AS average FROM (SELECT EXTRACT(EPOCH FROM (i.finish_date - i.start_date) / 60) AS minutes FROM c3p.inspection i WHERE i.state = 'FINISHED') as total_minutes\n"
    }
   ]
  },
  {
   "title": "Percentage finished this week",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT total_finished.count_finished * 100 / total_pending.count_pending AS percentage FROM \n(SELECT\n  Count(i.inspection_id) AS count_pending\n  FROM c3p.inspection i\n  WHERE \n  (i.start_date < current_date - interval '7 days' and i.finish_date isnull) or i.start_date > current_date - interval '7 days') AS total_pending\n  ,\n  (SELECT\n  Count(i.inspection_id) as count_finished\n  from c3p.inspection i\n  where i.start_date > current_date - interval '7 days' and i.finish_date is not null) AS total_finished;\n"
    }
   ]
  },
  {
   "title": "Total per finish type",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT now() as time, UNNEST(ARRAY['Without Novelty', 'With Novelty and Improvement action', 'With Novelty and without Improvement action']) AS metric, UNNEST(ARRAY[count1.count_without_novelty, with_novelty_and_improvement_action, with_novelty_and_without_improvement_action]) AS count\nFROM \n    (SELECT count(*) AS count_without_novelty\n        FROM c3p.inspection i\n        WHERE i.state = 'FINISHED' AND i.novelty = FALSE) AS count1,\n    (SELECT count(inspection_id) FILTER (WHERE count_improvement_action > 0) AS with_novelty_and_improvement_action, count(inspection_id) FILTER (WHERE count_improvement_action = 0) AS with_novelty_and_without_improvement_action\n        FROM (SELECT inspection_id, sum(ia.improvement_action::int) AS count_improvement_action\n                FROM c3p.inspection_activity ia\n                GROUP BY ia.inspection_id) AS improvement_action\n        ) AS count_with_novelty;"
    }
   ]
  },
  {
   "title": "Total per Status",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT now() as time, count(*), i.state as metric FROM c3p.inspection i GROUP BY i.state;"
    }
   ]
  },
  {
   "title": "Finished by time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(finish_date,$__interval),\n  state AS metric,\n  count(inspection_id) AS \"inspecciones\"\nFROM c3p.inspection\nWHERE\n  $__timeFilter(finish_date) AND\n  state = 'FINISHED'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}